version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: syscatalyst
      POSTGRES_DB: shoppingCard
      POSTGRES_USER: syscatalyst
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
